In [2]:
import numpy as np


In [3]:
#create array
x = np.array(range(10))
x=x.reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [4]:
x.shape

(2, 5)

# create another array and perform matrix multiply

In [5]:
w= np.array(range(10))
w=w.reshape(5,2)
y = np.matmul(x,w)
print(y)            

[[ 60  70]
 [160 195]]


In [6]:
yT = y.T
print(yT)

[[ 60 160]
 [ 70 195]]


In [7]:
z = np.matmul(y,yT)
print(z)

[[ 8500 23250]
 [23250 63625]]


In [10]:
print(z**(0.5))

[[  92.19544457  152.47950682]
 [ 152.47950682  252.23996511]]
